version: '3.4'

services:
  booksapi:
    image: ${DOCKER_REGISTRY-}booksapi
    build:
      context: .
      dockerfile: BooksAPI/Dockerfile
    ports:
      - "5500:5500"
      - "5501:5501"

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "BooksDB2"
    ports:
      - "5432:5432"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"